#!/usr/bin/env python3
"""Audit script: validation reports freshness and coherence.

Checks whether the validation suite scores can be trusted before relying on
them in code review or documentation.

Usage (from repo root):
    python scripts/simulation/audit_validation_freshness.py

Exit codes:
    0 — all critical checks passed (warnings may exist)
    1 — at least one CRITICAL issue found:
          - JSON parse error
          - report missing for a case that has a baseline
          - score mismatch between ESTADO_SESION and reference_checks.json
          - baseline.all_pass=False for a required case

Does NOT modify any file.  Read-only.
"""

from __future__ import annotations

import datetime
import json
import os
import re
import sys
from pathlib import Path
from typing import Any

# Force UTF-8 output so box-drawing characters and special symbols render on
# Windows terminals that default to cp1252.
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[attr-defined]
except AttributeError:
    pass  # Python < 3.7 fallback — output may degrade gracefully

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parents[2]
CASES_DIR   = ROOT / "sim" / "validation" / "cases"
BASELINES_DIR = ROOT / "sim" / "validation" / "baselines"
REPORTS_DIR = ROOT / "sim" / "validation" / "reports"
REF_CHECKS  = REPORTS_DIR / "reference_checks.json"
ESTADO_FILE = ROOT / "ESTADO_SESION_2026-05-21.md"

# Cases that intentionally have no baseline file.
# They are validated by reference_checks.json (CFAST point checks) or
# are exploratory/debug/calibration runs not part of the gating suite.
KNOWN_NO_BASELINE: set[str] = {
    # ── CFAST scenario cases (validated via reference_checks, not case baseline) ──
    "cfast_door_close_midfire",
    "cfast_fast_growth_closed",
    "cfast_hvac_residential",
    "cfast_long_burnout_3600s",
    "cfast_multi_fuel_couch_tv",
    "cfast_post_flashover_vented",
    "cfast_single_room_closed",
    "cfast_two_floor_stairwell",
    "cfast_two_room_door_open",
    "cfast_window_break_t180",
    # ── Calibration / comparison targets (not gating) ──
    "fds_simple_house_calibrated",
    "fds_simple_house_default",
    # ── Qualitative / exploratory ──
    "ghanekar_bedroom_hallway",
    "long_smoke_o2_1800",
    "long_smoke_o2_debug",
    "tmp_r0_window_open_start",
    # ── Window matrix exploratory cases ──
    "window_matrix_cocina_pulse",
    "window_matrix_dormitorios_crossvent",
    "window_matrix_ghanekar_remote",
    "window_matrix_salon_confined",
    "window_matrix_salon_pulse",
    "window_matrix_salon_spread_enabled",
    "window_matrix_salon_spread_stress",
}

# Reports that have no matching case file — generated by ad-hoc runs or
# sweep tools.  Not an error.
KNOWN_ORPHAN_REPORTS: set[str] = {
    "dt_sweep_living_room_hallway_dt0_5",
    "dt_sweep_living_room_hallway_dt1",
    "dt_sweep_living_room_hallway_dt2",
    "dt_sweep_living_room_hallway_dt5",
    "dt_sweep_living_room_hallway_dt10",
    "dt_sweep_living_room_hallway_dt20",
}

# Required baseline fields.
REQUIRED_REPORT_FIELDS = {"case", "metrics", "baseline"}

# ---------------------------------------------------------------------------
# Severity levels
# ---------------------------------------------------------------------------
CRITICAL = "CRITICAL"
WARNING  = "WARNING"
INFO     = "INFO"
OK       = "OK"

_LEVEL_ORDER = {CRITICAL: 0, WARNING: 1, INFO: 2, OK: 3}


class Issue:
    def __init__(self, level: str, category: str, name: str, detail: str) -> None:
        self.level    = level
        self.category = category
        self.name     = name
        self.detail   = detail

    def __lt__(self, other: "Issue") -> bool:
        return (_LEVEL_ORDER[self.level], self.category, self.name) < \
               (_LEVEL_ORDER[other.level], other.category, other.name)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
W = 80

def _heading(text: str) -> None:
    print("\n" + "=" * W)
    print(f"  {text}")
    print("=" * W)


def _section(text: str) -> None:
    print("\n" + "-" * W)
    print(f"  {text}")
    print("-" * W)


def _fmt_dt(ts: float) -> str:
    return datetime.datetime.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M:%S")


def _has_bom(path: Path) -> bool:
    """Return True if the file starts with a UTF-8 BOM byte sequence."""
    try:
        with path.open("rb") as fh:
            return fh.read(3) == b"\xef\xbb\xbf"
    except OSError:
        return False


def _load_json_safe(path: Path) -> tuple[dict[str, Any] | None, str | None]:
    """Return (parsed_dict, None) or (None, error_message).

    Uses utf-8-sig encoding so files with or without a BOM both parse cleanly.
    The BOM is handled transparently here; it is reported separately as INFO via
    check_bom_presence() when relevant.
    """
    try:
        return json.loads(path.read_text(encoding="utf-8-sig")), None
    except Exception as exc:
        return None, str(exc)


def _mtime(path: Path) -> float:
    return path.stat().st_mtime if path.exists() else 0.0


# ---------------------------------------------------------------------------
# Collection helpers
# ---------------------------------------------------------------------------

def _collect_cases() -> dict[str, Path]:
    return {p.stem: p for p in sorted(CASES_DIR.glob("*.json"))}


def _collect_baselines() -> dict[str, Path]:
    return {p.stem: p for p in sorted(BASELINES_DIR.glob("*.json"))}


def _collect_reports() -> dict[str, Path]:
    return {
        p.stem: p
        for p in sorted(REPORTS_DIR.glob("*.json"))
        if p.stem != "reference_checks"
    }


# ---------------------------------------------------------------------------
# Individual checks
# ---------------------------------------------------------------------------

def check_json_parse_errors(
    cases: dict[str, Path],
    baselines: dict[str, Path],
    reports: dict[str, Path],
    issues: list[Issue],
) -> None:
    """Every JSON file must parse cleanly (using utf-8-sig to tolerate BOM)."""
    for label, mapping in [("case", cases), ("baseline", baselines), ("report", reports)]:
        for name, path in mapping.items():
            _, err = _load_json_safe(path)
            if err:
                issues.append(Issue(CRITICAL, "parse_error", name,
                                    f"{label} JSON unparseable: {err}"))

    ref_data, err = _load_json_safe(REF_CHECKS)
    if err:
        issues.append(Issue(CRITICAL, "parse_error", "reference_checks",
                            f"reference_checks.json unparseable: {err}"))


def check_bom_presence(
    baselines: dict[str, Path],
    issues: list[Issue],
) -> None:
    """Report baseline files that contain a UTF-8 BOM as INFO.

    BOM does not affect Godot (which reads the files) or validate_reference_cases.py
    (which reads only reports/).  It can trip up naïve Python readers that use
    encoding='utf-8' instead of 'utf-8-sig'.  No action required unless a new
    Python tool needs to read these files.
    """
    bom_files = [name for name, path in sorted(baselines.items()) if _has_bom(path)]
    if bom_files:
        issues.append(Issue(INFO, "utf8_bom", "baselines",
                            f"{len(bom_files)} baseline file(s) have UTF-8 BOM — "
                            f"transparent to Godot and validate_reference_cases.py, "
                            f"but use encoding='utf-8-sig' in any Python tooling: "
                            + ", ".join(bom_files[:6])
                            + (f" (+{len(bom_files)-6} more)" if len(bom_files) > 6 else "")))


def check_missing_reports(
    cases: dict[str, Path],
    baselines: dict[str, Path],
    reports: dict[str, Path],
    issues: list[Issue],
) -> None:
    """Every case that has a baseline must have a report (required for scoring)."""
    for name in sorted(baselines):
        if name not in reports:
            issues.append(Issue(CRITICAL, "missing_report", name,
                                "has baseline but NO report — case needs re-running"))
    # Cases without either a baseline or a report → pure info
    for name in sorted(cases):
        if name not in baselines and name not in KNOWN_NO_BASELINE:
            if name not in reports:
                issues.append(Issue(WARNING, "missing_report", name,
                                    "case has no baseline and no report (new / unconfigured)"))
            else:
                issues.append(Issue(INFO, "no_baseline", name,
                                    "case has report but no baseline — not yet gated"))
        elif name in KNOWN_NO_BASELINE and name not in reports:
            issues.append(Issue(INFO, "no_report", name,
                                "exploratory/CFAST case — no report yet (not critical)"))


def check_orphan_reports(
    cases: dict[str, Path],
    reports: dict[str, Path],
    issues: list[Issue],
) -> None:
    """Reports that have no matching case file."""
    for name in sorted(reports):
        if name not in cases:
            if name in KNOWN_ORPHAN_REPORTS:
                issues.append(Issue(INFO, "orphan_report", name,
                                    "report with no case file (dt_sweep or ad-hoc run)"))
            else:
                issues.append(Issue(WARNING, "orphan_report", name,
                                    "report has no matching case JSON — unexpected"))


def check_staleness(
    cases: dict[str, Path],
    baselines: dict[str, Path],
    reports: dict[str, Path],
    issues: list[Issue],
) -> None:
    """Reports that are older than their case or baseline file (mtime-based)."""
    for name, rpt_path in sorted(reports.items()):
        rt = _mtime(rpt_path)
        older_than: list[str] = []

        if name in cases:
            ct = _mtime(cases[name])
            if rt < ct:
                older_than.append(f"case ({_fmt_dt(ct)} > report {_fmt_dt(rt)})")

        if name in baselines:
            bt = _mtime(baselines[name])
            if rt < bt:
                older_than.append(f"baseline ({_fmt_dt(bt)} > report {_fmt_dt(rt)})")

        if older_than:
            detail = "report predates: " + "; ".join(older_than)
            issues.append(Issue(WARNING, "stale_report", name, detail))

    # Also check if any report is newer than reference_checks.json
    if REF_CHECKS.exists():
        rc_mtime = _mtime(REF_CHECKS)
        newer_reports = [
            name for name, rpt in reports.items()
            if _mtime(rpt) > rc_mtime
        ]
        if newer_reports:
            issues.append(Issue(WARNING, "stale_reference_checks", "reference_checks",
                                f"{len(newer_reports)} report(s) are newer than "
                                f"reference_checks.json — re-run validate_reference_cases.py: "
                                + ", ".join(sorted(newer_reports)[:10])))


def check_report_fields(
    reports: dict[str, Path],
    issues: list[Issue],
) -> None:
    """Every report must have the minimum required fields."""
    for name, path in sorted(reports.items()):
        data, err = _load_json_safe(path)
        if data is None:
            continue  # already reported in parse check
        missing = REQUIRED_REPORT_FIELDS - set(data.keys())
        if missing:
            issues.append(Issue(CRITICAL, "missing_fields", name,
                                f"missing fields: {sorted(missing)}"))


def check_baseline_all_pass(
    reports: dict[str, Path],
    baselines: dict[str, Path],
    issues: list[Issue],
) -> None:
    """Baseline checks should all pass for cases that have a baseline."""
    for name, path in sorted(reports.items()):
        if name not in baselines:
            continue  # no baseline → not gated
        data, err = _load_json_safe(path)
        if data is None:
            continue
        bl = data.get("baseline", {})
        if bl.get("all_pass") is False:
            failing = [k for k, v in bl.get("checks", {}).items()
                       if not v.get("pass", True)]
            issues.append(Issue(WARNING, "baseline_failing", name,
                                f"baseline.all_pass=False — failing checks: {failing}"))


def check_score_coherence(issues: list[Issue]) -> dict[str, Any]:
    """Compare reference_checks.json actual score vs ESTADO_SESION documented score."""
    result: dict[str, Any] = {}

    # Load reference_checks
    rc_data, err = _load_json_safe(REF_CHECKS)
    if rc_data is None:
        return result  # parse error already reported
    result["actual_required"] = rc_data.get("required_count", "?")
    result["actual_failed"]   = rc_data.get("failed_required_count", "?")
    result["actual_gaps"]     = rc_data.get("known_gap_count", "?")
    result["actual_pass"]     = rc_data.get("all_required_pass", False)
    result["rc_mtime"]        = _mtime(REF_CHECKS)

    # Extract documented score from ESTADO file
    result["estado_score_line"] = None
    result["estado_required"]   = None
    result["estado_gaps"]       = None

    if ESTADO_FILE.exists():
        text = ESTADO_FILE.read_text(encoding="utf-8", errors="replace")
        m = re.search(r"PASS:\s*(\d+)/(\d+)\s*required checks passed", text)
        if m:
            result["estado_score_line"] = m.group(0)
            result["estado_required"]   = int(m.group(1))   # N passed
            result["estado_total"]      = int(m.group(2))   # total required
        m2 = re.search(r"gaps:\s*(\d+)\s*non-gating", text)
        if m2:
            result["estado_gaps"] = int(m2.group(1))
    else:
        issues.append(Issue(WARNING, "score_coherence", "estado_file",
                            f"ESTADO_SESION_2026-05-21.md not found — cannot compare scores"))
        return result

    # Compare
    actual_req = result["actual_required"]
    actual_fail = result["actual_failed"]
    actual_pass_count = actual_req - actual_fail if isinstance(actual_req, int) else None

    if actual_pass_count is not None and result.get("estado_required") is not None:
        if actual_pass_count != result["estado_required"]:
            issues.append(Issue(CRITICAL, "score_coherence", "score_mismatch",
                                f"ESTADO documents {result['estado_required']}/{result['estado_total']} "
                                f"but reference_checks has {actual_pass_count}/{actual_req} required passing"))
        else:
            # Check gap count
            if result.get("estado_gaps") is not None and result["estado_gaps"] != result["actual_gaps"]:
                issues.append(Issue(WARNING, "score_coherence", "gap_count_mismatch",
                                    f"ESTADO documents {result['estado_gaps']} gaps "
                                    f"but reference_checks has {result['actual_gaps']} non-gating"))

    return result


def collect_cfast_structural_gaps(issues: list[Issue]) -> list[dict[str, Any]]:
    """Return the list of CFAST non-gating checks that are currently failing."""
    rc_data, err = _load_json_safe(REF_CHECKS)
    if rc_data is None:
        return []
    all_checks = rc_data.get("checks", [])
    cfast_gaps = [
        c for c in all_checks
        if not c.get("required", True) and c.get("name", "").startswith("cfast_")
    ]
    return cfast_gaps


# ---------------------------------------------------------------------------
# Report printer
# ---------------------------------------------------------------------------

def _print_issues_by_category(issues: list[Issue]) -> None:
    from itertools import groupby

    by_cat = {}
    for iss in sorted(issues):
        by_cat.setdefault(iss.category, []).append(iss)

    for category, items in sorted(by_cat.items(), key=lambda x: min(_LEVEL_ORDER[i.level] for i in x[1])):
        has_critical = any(i.level == CRITICAL for i in items)
        has_warning  = any(i.level == WARNING  for i in items)
        prefix = "[CRIT]" if has_critical else ("[WARN]" if has_warning else "[ ok ]")
        _section(f"{prefix}  {category.upper()} ({len(items)} items)")
        for iss in items:
            tag = f"[{iss.level[:4]}]"
            print(f"  {tag:<8} {iss.name:<40}  {iss.detail}")


def _print_summary(issues: list[Issue], score_info: dict[str, Any]) -> None:
    _heading("AUDIT SUMMARY")

    criticals = [i for i in issues if i.level == CRITICAL]
    warnings  = [i for i in issues if i.level == WARNING]
    infos     = [i for i in issues if i.level == INFO]

    print(f"  Critical issues : {len(criticals)}")
    print(f"  Warnings        : {len(warnings)}")
    print(f"  Informational   : {len(infos)}")

    _section("Score coherence")
    rc_t = score_info.get("rc_mtime")
    rc_t_str = _fmt_dt(rc_t) if rc_t else "?"
    print(f"  reference_checks.json  ({rc_t_str})")
    print(f"    required : {score_info.get('actual_required', '?')}")
    print(f"    failed   : {score_info.get('actual_failed', '?')}")
    print(f"    gaps     : {score_info.get('actual_gaps', '?')}")
    print(f"    all_pass : {score_info.get('actual_pass', '?')}")
    if score_info.get("estado_score_line"):
        print(f"  ESTADO_SESION documents : {score_info['estado_score_line']}")
        print(f"    gaps (ESTADO)          : {score_info.get('estado_gaps', '?')}")
    mismatch = any(i.category == "score_coherence" and i.level == CRITICAL for i in issues)
    print(f"  Score match : {'FAIL ← MISMATCH' if mismatch else 'OK'}")


def _print_stale_recommendations(issues: list[Issue]) -> None:
    stale = [i for i in issues if i.category == "stale_report" and i.level == WARNING]
    base_fail = [i for i in issues if i.category == "baseline_failing"]
    if not stale and not base_fail:
        return

    _section("Recommended re-runs")
    regenerate: list[str] = []

    if stale:
        print("  Cases with stale reports (re-run to refresh):")
        for iss in sorted(stale, key=lambda x: x.name):
            print(f"    {iss.name}")
            regenerate.append(iss.name)

    if base_fail:
        print()
        print("  Cases with baseline.all_pass=False (re-run and rebaseline if results changed):")
        for iss in sorted(base_fail, key=lambda x: x.name):
            fails = iss.detail.split("failing checks: ")[-1]
            print(f"    {iss.name}  → {fails}")
            if iss.name not in regenerate:
                regenerate.append(iss.name)

    if regenerate:
        print()
        print("  PowerShell commands (from sim\\validation\\):")
        for name in sorted(set(regenerate)):
            print(f"    powershell -ExecutionPolicy Bypass -File run_case.ps1 -CaseName {name} -TimeoutSeconds 300")
        print()
        print("  After re-running:")
        print("    python scripts/simulation/validate_reference_cases.py")


def _print_cfast_structural_gaps(cfast_gaps: list[dict[str, Any]]) -> None:
    failing = [c for c in cfast_gaps if not c.get("pass", True)]
    passing = [c for c in cfast_gaps if c.get("pass", True)]
    _section(f"CFAST structural non-gating checks ({len(cfast_gaps)} total, "
             f"{len(failing)} failing, {len(passing)} passing)")
    print(f"  These are expected architectural gaps (one-zone vs two-zone).")
    print(f"  All are required=False and do NOT affect the 292/292 required score.")
    print()

    if failing:
        print(f"  Failing ({len(failing)})  — needs Phase 2 to resolve:")
        for c in sorted(failing, key=lambda x: x.get("name", "")):
            note = c.get("note", "")
            note_short = (note[:65] + "…") if len(note) > 65 else note
            print(f"    {'[GAP]':<8} {c.get('name',''):<40}  {note_short}")

    if passing:
        print()
        print(f"  Passing ({len(passing)})  — within tolerance despite architecture gap:")
        for c in sorted(passing, key=lambda x: x.get("name", "")):
            print(f"    {'[OK]':<8} {c.get('name','')}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    _heading("Validation Freshness Audit - SimuFire")
    print(f"  Root   : {ROOT}")
    print(f"  Run at : {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    cases     = _collect_cases()
    baselines = _collect_baselines()
    reports   = _collect_reports()

    _section(f"Inventory")
    print(f"  Case files     : {len(cases)}")
    print(f"  Baseline files : {len(baselines)}")
    print(f"  Report files   : {len(reports)} (excl. reference_checks)")
    if not REF_CHECKS.exists():
        print(f"  reference_checks.json : MISSING")
    else:
        rc_age_s = (datetime.datetime.now().timestamp() - _mtime(REF_CHECKS))
        rc_age_h = rc_age_s / 3600
        age_str = f"{rc_age_h:.1f}h ago" if rc_age_h < 24 else f"{rc_age_h/24:.1f}d ago"
        print(f"  reference_checks.json : {_fmt_dt(_mtime(REF_CHECKS))} ({age_str})")

    issues: list[Issue] = []

    check_json_parse_errors(cases, baselines, reports, issues)
    check_bom_presence(baselines, issues)
    check_missing_reports(cases, baselines, reports, issues)
    check_orphan_reports(cases, reports, issues)
    check_staleness(cases, baselines, reports, issues)
    check_report_fields(reports, issues)
    check_baseline_all_pass(reports, baselines, issues)
    score_info = check_score_coherence(issues)

    cfast_gaps = collect_cfast_structural_gaps(issues)

    _section("Issues by category")
    if issues:
        _print_issues_by_category(issues)
    else:
        print("  No issues found.")

    _print_cfast_structural_gaps(cfast_gaps)
    _print_stale_recommendations(issues)
    _print_summary(issues, score_info)

    # --- Determine exit code ---
    critical_count = sum(1 for i in issues if i.level == CRITICAL)
    if critical_count > 0:
        print(f"\n  Exit 1 - {critical_count} critical issue(s) found.")
        return 1
    else:
        print(f"\n  Exit 0 - no critical issues.  Suite score is trustworthy.")
        return 0


if __name__ == "__main__":
    sys.exit(main())
